# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/gta4xls/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),gta4xls)

$(call add-radio-file-sha1-checked,radio/cm.bin_SM-P615,)
$(call add-radio-file-sha1-checked,radio/keystorage.bin_SM-P615,)
$(call add-radio-file-sha1-checked,radio/models,)
$(call add-radio-file-sha1-checked,radio/modem.bin_SM-P615,)
$(call add-radio-file-sha1-checked,radio/modem_debug.bin_SM-P615,)
$(call add-radio-file-sha1-checked,radio/sboot.bin_SM-P615,)
$(call add-radio-file-sha1-checked,radio/uh.bin_SM-P615,)
$(call add-radio-file-sha1-checked,radio/up_param.bin_SM-P615,)
$(call add-radio-file-sha1-checked,radio/version_SM-P615,)

endif
