# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/gta4xls/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),gta4xls)

$(call add-radio-file-sha1-checked,radio/fld.bin_SM-P625,714c8a3f5179a4d7d98a6d2681790488bcda356e)
$(call add-radio-file-sha1-checked,radio/harx.bin_SM-P625,131d1d5e6ea6510d083c7768a80efad13c1993d6)
$(call add-radio-file-sha1-checked,radio/keystorage.bin_SM-P625,da0aeb9d349f4634f8c9b3a520015681367715f4)
$(call add-radio-file-sha1-checked,radio/ldfw.img_SM-P625,9cb45eabd8b3dcca402c3fd67dfe8cb9f5512b49)
$(call add-radio-file-sha1-checked,radio/models,bcb68e48eb0d20cc86c4c529c7051199c1b49550)
$(call add-radio-file-sha1-checked,radio/modem.bin_SM-P625,6bf23cf61357261b6e98a050706ff44d91ed0921)
$(call add-radio-file-sha1-checked,radio/modem_debug.bin_SM-P625,3ecf396d348472cb7aa6f698cdc47baaf7257e56)
$(call add-radio-file-sha1-checked,radio/sboot.bin_SM-P625,a259d21dae6836adf239f4e002a7fd7fb44e05f9)
$(call add-radio-file-sha1-checked,radio/tzar.img_SM-P625,39476aef3141e6238099814846365dbf869d5d3c)
$(call add-radio-file-sha1-checked,radio/tzsw.img_SM-P625,5520442eeaceca377976a6856749885ad92f2ce8)
$(call add-radio-file-sha1-checked,radio/uh.bin_SM-P625,55365d70a2ecb3f812b134566728146101a0b371)
$(call add-radio-file-sha1-checked,radio/up_param.bin_SM-P625,7b643fe70a7c340b9cabcc95af4ab4081888897c)
$(call add-radio-file-sha1-checked,radio/version_SM-P625,1f88a3d690daef0704a2e5ddc8e5d3ef169ee721)

endif
